### ISSUE TITLE
日志那块文件名写反了

### ISSUE THREAD

**Issue by chenglongzjg** [superalsrk/springboot-practice#1]
文件名必须是 logback-spring.xml 而不是 spring-logback.xml
另: springProfile 啥作用？

**Comment by superalsrk** [comment]
谢谢。。README上的错误已经修正

SpringProfile的资料可以参考这个： https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html

简单解释就一般来说本地开发和线上部署和测试环境的配置是不同的(比如mysql, redis, mq的地址)， 通过使用Profile可以在同一套代码里配置不同环境的配置文件, 只需要在运行的时候指定到底是 production, test, develop 之中的哪种环境即可

另外对于Spring来讲, @Profile注解 是可以放在 @Bean上的, 这样就会有一个很棒的特性, 对于实现同一套接口的两个BeanA, BeanB, 可以配置成BeanA只在production环境初始化, BeanB只在test环境初始化

over

**Comment by chenglongzjg** [comment]
嗯 3q。 不过下面那个似乎用不着啊？ 
我现在只用  spring.profiles.active 指定一下 dev 与 prod

**Comment by superalsrk** [comment]
一些情况下还是可以用的。。比如说一般来说程序里需要有一个DataSource, 通过@Bean + @Profile, 可以再dev环境用sqlite datasource， prod环境用mysql datasource

**Comment by chenglongzjg** [comment]
不用啊 spring.profiles.active 指定 dev，然后 dev里用一个 datasource 配置  prod 中是另一个datasource 配置
