### ISSUE TITLE
springboot-demo-jpa-mybatis 明显项目和名字不对应

### ISSUE THREAD

**Issue by chenglongzjg** [superalsrk/springboot-practice#2]
标题讲项目 是 jpa 和 mybatis 同时使用， but， 你确定你不是在逗我？整个项目连 mybatis 的依赖都没有。项目里更是毫无 mybatis 相关，甚至没有 jpa 相关。

**Comment by superalsrk** [comment]
..额。好久没更了 有一半的子项目都还没写, 抱歉

**Comment by superalsrk** [comment]
上半年应该会慢慢更

**Comment by chenglongzjg** [comment]
那你可以在项目后面写个备注：已完成、未完成以及正在code

**Comment by superalsrk** [comment]
好的。。谢谢建议

**Comment by chenglongzjg** [comment]
我和你一起写吧 正好最近再用相关的东西
